config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'

  # root 'pages#home'

  devise_for :teachers, :controllers => {:registrations => 'teachers/registrations'}

  devise_for :users,
						 :path => '',
						 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
						 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
						 									:registrations => 'registrations'
						 								 }

  resources :users, only: [:show]

  resources :teachers, only: [:show, :index] do
    resources :subjects, only: [:new, :create] do
      resources :schedules, only: [:index]
    end
  end

  resources :photos
  resources :checkouts, only: [:new, :create]

  resources :teachers do
  	resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
  <!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">the<b>muzed</b></a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">


        <% if(!user_signed_in? && !teacher_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>

          <li><%= link_to "Teacher Log In", new_teacher_session_path %></li>
          <li>
            <a href="/teachers/sign_up"><i class="fa fa-music fa-lg" aria-hidden="true"></i> Become our Teacher</a>
          </li>
        <% elsif (!teacher_signed_in?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" id="superdropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %><span class="caret"></span></a>

            <ul class="dropdown-menu" aria-labelledby="superdropdown">
              <li><%= link_to "Your Profile", user_path(current_user.id) %></li>
              <li><a href="#">Wish Lists</a></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Account Setting</a></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "My Profile", teacher_path(current_teacher.id) %></li>
        <% end %>

        <li>
          <%= link_to conversations_path do %>
            <i class="fa fa-envelope-o" aria-hidden="true"></i> Messages
          <% end %>
        </li>
        <li><%= link_to "Search For Teacher", teachers_path %></li>
      </ul>

    </div><!--/.nav-collapse -->
  </div>
</nav>