config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'

  # root 'pages#home'

  devise_for :teachers, :controllers => {:registrations => 'teachers/registrations'}

  devise_for :users,
						 :path => '',
						 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
						 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
						 									:registrations => 'registrations'
						 								 }

  resources :users, only: [:show]

  resources :teachers, only: [:show, :index] do
    resources :subjects, only: [:new, :create] do
      resources :schedules, only: [:index]
    end
  end

  resources :photos
  resources :checkouts, only: [:new, :create]

  resources :teachers do
  	resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  searchkick locations: ["location"]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos

  has_many :reservations

  has_many :subjects
  has_many :timeslots
  has_many :users, through: :timeslots
  after_save :reindex_item


  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

	# validates :education, presence: true
  # validates :biography, presence: true, length: {maximum: 500}
  # validates :teaching_statement, presence: true, length: {maximum: 100}
  # validates :address, presence: true
  # validates :ages_taught, presence: true
  # validates :levels_taught, presence: true
  # validates :languages, presence: true
  # validates :lesson_locations, presence: true
  # validates :hourly_rate, presence: true, numericality: true

  def reindex_item
    reindex
  end

  def search_data
    attributes.merge(
      location: [latitude, longitude],
      subjects: subjects.map(&:title),
      levels: subjects.map(&:level)
    )
  end
end

app/controllers/teachers/registrations_controller.rb
class Teachers::RegistrationsController < Devise::RegistrationsController
  before_action :change_params, only: :create

  private

  def change_params
    params[:teacher][:languages] = params[:teacher][:languages].join(", ")
  end

  # def sign_up_params
  #   params.require(:teacher).permit(:email, :password, :password_confirmation, :ages_taught, :languages, :lesson_locations, :teaching_statement, :biography, :education, :address, :teach_special_needs, :active)
  # end
  #
  # def account_update_params
  #   params.require(:teacher).permit(:email, :password, :password_confirmation, :current_password)
  # end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update]
  before_action :authenticate_teacher!, except: [:show, :index]

  def index
    params[:subjects] ||= ["Piano", "Violin", "Vocal"]
    params[:levels] ||= ["Beginner", "Intermediate", "Advanced", "Diploma"]
    if params[:search]
      @teachers = Teacher.search("*", where: {
        location: { near: Geocoder.coordinates(params[:search][:search_place]), within: '20mi' },
        subjects: params[:subjects],
        levels: params[:levels]
      })
    else
      @teachers = Teacher.all
    end
  end

  def show
    @teachers = Teacher.all
    @photos = @teacher.photos
  end

  def edit
    if current_user.id == @teacher.user.id
    @photos = @teacher.photos
    else
      redirect_to root_path, notice: "You don't have permission"
    end
  end

  def update
    if @teacher.update(teacher_params)

      if params[:images]
        params[:images].each do |image|
          @teacher.photos.create(image: image)
        end
      end

      redirect_to edit_teacher_path(@teacher), notice: "Your teacher's profile is updated!"
    else
      render :edit
    end
  end

  private
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    def teacher_params
      params.require(:teacher).permit(:subject, :education, :biography, :teaching_statement, :address, :ages_taught, :levels_taught, :languages, :lesson_locations, :hourly_rate, :teach_special_needs, :active)
    end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Create your beautiful profile
	</div>
	<div class="panel-body">
		<div class="container">

			<div class="row">
					<div class="form-group">
						<label>Ages Taught</label>
						<%= f.check_box :ages_taught, { class: 'form-control', multiple: true }, "Children", nil %>
						<%= f.label :ages_taught, "Children" %>
						<%= f.check_box :ages_taught, { class: 'form-control', multiple: true }, "Teens", nil %>
						<%= f.label :ages_taught, "Teens" %>
						<%= f.check_box :ages_taught, { class: 'form-control', multiple: true }, "Adults", nil %>
						<%= f.label :ages_taught, "Adults" %>
						<%= f.check_box :ages_taught, { class: 'form-control', multiple: true }, "All Ages", nil %>
						<%= f.label :ages_taught, "All Ages" %>
					</div>
			</div>

			<div class="row">
					<div class="form-group">
						<label>Languages</label>
						<%= f.check_box :languages, { class: 'form-control', multiple: true }, "English", nil %>
						<%= f.label :languages, "English" %>
						<%= f.check_box :languages, { class: 'form-control', multiple: true }, "Chinese", nil %>
						<%= f.label :languages, "Chinese" %>
						<%= f.check_box :languages, { class: 'form-control', multiple: true }, "Malay", nil %>
						<%= f.label :languages, "Malay" %>
						<%= f.check_box :languages, { class: 'form-control', multiple: true }, "Tamil", nil %>
						<%= f.label :languages, "Tamil" %>
					</div>
			</div>

				<div class="col-md-4 select">
					<div class="form-group">
						<label>Lesson Locations</label>
						<%= f.select :lesson_locations, [["Teacher's Studio","Teacher's Studio"], ["Student's Place","Student's Place"], ["Common Ground","Common Ground"]], prompt: "Select...", class: "form-control" %>
					</div>
				</div>


			<div class="row">
				<div class="form-group">
					<label>Teaching Statement</label>
					<%= f.text_field :teaching_statement, placeholder: "Short and concise", class: "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group">
					<label>Biography</label>
					<%= f.text_area :biography, rows: 5, placeholder: "About yourself and your achievement", class: "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group">
					<label>Education</label>
					<%= f.text_area :education, rows: 5, placeholder: "Education background", class: "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group">
					<label>Address</label>
					<%= f.text_field :address, placeholder: "Your house/studio address", class: "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<%= f.check_box :teach_special_needs %> Do you teach special needs?
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<span class="btn btn-default btn-file">
						    <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos
						    <%= file_field_tag "images[]", type: :file, multiple: true %>
						</span>
					</div>
				</div>
			</div>

			<div id="photos"><%= render 'photos/list' %></div>

			<div class="row">
				<div class="form-group">
					<%= f.check_box :active %> Active
				</div>
			</div>


		</div>
	</div>
</div>

app/views/teachers/_schedule.html.erb
<a class="pressable" data-toggle="modal" data-target="#schedule-<%= subject.id %>"><%= subject.title + " - " + subject.level %></a><br>

<div class="modal fade" id="schedule-<%= subject.id %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <% subject.schedules.each do |schedule| %>
          <div class="row">
            <div class="col-md-2">
              <%= schedule.date.strftime("%d %B") %>
            </div>
            <div class="col-md-7">
              <% schedule.timeslots.each do |timeslot| %>
                <% if !timeslot.booked? %>
                  <h4><%= timeslot.time.strftime("%I:%M %P") %> - RM<%= timeslot.schedule.subject.hourly_rate %></h4>
                  <%=link_to "Book now!", new_checkout_path(timeslot: timeslot.id), class:"btn btn-lg success"%>
                  <hr>
                <% end %>
              <% end %>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/teachers/create.html.erb
<h1>Teachers#create</h1>
<p>Find me in app/views/teachers/create.html.erb</p>

app/views/teachers/edit.html.erb
<%= render 'form' %>

app/views/teachers/index(old).html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listed Subjects", teachers_path, class: "sidebar-link active" %></li>
			<li class="sidebar-item"><%= link_to "Your Reservations", teachers_path, class: "sidebar-link" %></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Listed Subjects
			</div>
			<div class="panel-body">
				
				<% @teacher.each do |teacher| %>
					<div class="row">
						<div class="col-md-2">
							<%= image_tag teacher.photos[0].image.url(:thumb) if teacher.photos.length > 0 %>
						</div>		
						<div class="col-md-7">
							<h4><%= teacher.subject %></h4>
						</div>		
						<div class="col-md-3 right">
							<%= link_to "Update", edit_teacher_path(teacher), class: "btn btn-primary" %>
						</div>		
					</div>
					<hr>
				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/teachers/index.html.erb
<div class="panel-body">

  <%= form_for(:search, url: teachers_path, method: :get, html: { id: "search-teachers-form" }) do |f| %>

  <div class="field">
    <label>Your Area</label>
    <%= f.text_field :search_place, autofocus: true %>
  </div>

  <div class="dropdown">
    <button id="Categories_dropdown_subjects" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Subjects
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="Categories_dropdown_subjects">
      <li><%= check_box_tag(:'subjects[]', "Piano") %>
      <%= label_tag("Piano") %></li>
      <li role="separator" class="divider"></li>
      <li><%= check_box_tag(:'subjects[]', "Violin") %>
      <%= label_tag("Violin") %></li>
      <li role="separator" class="divider"></li>
      <li><%= check_box_tag(:'subjects[]', "Vocal") %>
      <%= label_tag("Vocal") %></li>
    </ul>
  </div>

  <div class="dropdown">
    <button id="Categories_dropdown_levels" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Levels
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="Categories_dropdown_levels">
      <li><%= check_box_tag(:'levels[]', "Beginner") %>
      <%= label_tag("Beginner") %></li>
      <li role="separator" class="divider"></li>
      <li><%= check_box_tag(:'levels[]', "Intermediate") %>
      <%= label_tag("Intermediate") %></li>
      <li role="separator" class="divider"></li>
      <li><%= check_box_tag(:'levels[]', "Advanced") %>
      <%= label_tag("Advanced") %></li>
      <li role="separator" class="divider"></li>
      <li><%= check_box_tag(:'levels[]', "Diploma") %>
      <%= label_tag("Diploma") %></li>
    </ul>
  </div>

  <div class="actions">
    <%= f.submit "Search" %>
  </div>

  <% end %>

  <% @teachers.each do |teacher| %>
    <div class="row">
      <div class="col-md-2">
        <%= link_to teacher.fullname, teacher_path(teacher.id) %>
        <%= image_tag teacher.photos[0].image.url(:thumb) if teacher.photos.length > 0 %>
      </div>
      <div class="col-md-7">
        <% teacher.subjects.each do |subject| %>
          <%= render partial: "schedule", locals: { subject: subject } %>
        <% end %>
      </div>
    </div>
    <hr>
  <% end %>


</div>

app/views/teachers/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">

		<!-- Image -->
		<div class="row">
			<div class="col-md-12">
				<%= image_tag @photos[0].image.url(), class: "img-responsive" if @photos.length > 0 %>
			</div>
		</div>

		<br>

		<!-- Main Info -->
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-3 text-center">

						<%= @teacher.fullname %>
					</div>

					<div class="col-md-9">
						<%= @teacher.address %>

						<div class="row text-center row-space-1">
							<div class="col-sm-3">
								<i class="fa fa-users fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-language fa-2x"></i>
							</div>
						</div>

						<div class="row text-center">
							<div class="col-sm-3">
								<%= @teacher.ages_taught %>
							</div>
							<div class="col-sm-3">
								<%= @teacher.languages %>
							</div>
						</div>

					</div>
				</div>
			</div>

		<!-- About -->
		<div class="row">
			<div class="col-md-12">
				<h2>Teaching Statement</h2>
				<p><%= @teacher.teaching_statement %></p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<h2>About The Teacher</h2>
				<p><%= @teacher.biography %></p>
				<h2>Education Background</h2>
				<p><%= @teacher.education %></p>
			</div>
		</div>

		<!-- Additional -->
		<div class="row">
			<div class="col-md-2">
				<p>Additional Info</p>
			</div>
			<div class="col-md-10">
				<div class="row">
					<div class="col-md-6">
						<ul class="additional">
							<li class="<%= 'text-line-through' if !@teacher.teach_special_needs %>">Teach Special Needs</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<!-- Carousel -->
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<div id="myCarousel" class="carousel slide" data-ride="carousel">

					<% if @photos %>
						<!-- Indicators -->
				    <ol class="carousel-indicators">
							<% @photos.each do |photo| %>
								<li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
							<% end %>
						</ol>
					<% end %>

				  <div class="carousel-inner" role="listbox">
				    <% if @photos %>
							<% @photos.each do |photo| %>
								<div class="item <%= 'active' if photo.id == @photos[0].id %>">
				          <%= image_tag photo.image.url() %>
				        </div>
							<% end %>
						<% end %>
				  </div>

				  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>
			</div>
		</div>

		<br>
		<hr>

		<!-- Google Map -->
		<div class="row">
			<div class="col-md-12">

				<div id="map"></div>

			<style>
		      #map {
		        width: 100%;
		        height: 400px;
		      }
		    </style>

		    <script async defer
		        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD4JumuERAO95zOPDF9Egs8-aQzOpaBhoU&callback=initMap">
		    </script>
		    <script>
					function initMap() {
						var mapDiv = document.getElementById('map');
						var map = new google.maps.Map(mapDiv, {
							center: {lat: <%= @teacher.latitude %>, lng: <%= @teacher.longitude %>},
							zoom: 14
							});
						var marker = new google.maps.Marker({
							position: {lat: <%= @teacher.latitude %>, lng: <%= @teacher.longitude %>},
							title: "TheMuzed"
							});
					marker.setMap(map);
					}

					google.maps.event.addDomListener(window, 'turbolinks:load', initMap);
		    </script>


			</div>
		</div>

		<!-- Close by Teachers -->
		<h3>Other teachers nearby</h3>
		<div class="row">
			<% for teacher in @teacher.nearbys(10) %>

				<div class="col-md-4">
					<div class="panel panel-default">
						<div class="panel-heading preview">
						</div>
						<div class="panel-body">
							<%= link_to teacher.fullname, teacher %><br>
							<% teacher.subjects.each do |subject| %>
								<%= subject.title + " - " + subject.level %><br>
							<% end %>
							(<%= teacher.distance.round(2) %> miles away)
						</div>
					</div>
				</div>

			<% end %>
		</div>
						<%= link_to "Add Subjects", new_teacher_subject_path(@teacher) %>
	</div>
</div>

app/views/teachers/update.html.erb
<h1>Teachers#update</h1>
<p>Find me in app/views/teachers/update.html.erb</p>