config/routes.rb
Rails.application.routes.draw do

  root to: 'landing#index'

  # root 'pages#home'

  devise_for :teachers, :controllers => {:registrations => 'teachers/registrations'}

  devise_for :users,
						 :path => '',
						 :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
						 :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
						 									:registrations => 'registrations'
						 								 }

  resources :users, only: [:show]

  resources :teachers, only: [:show, :index] do
    resources :subjects, only: [:new, :create] do
      resources :schedules, only: [:index]
    end
  end

  resources :photos
  resources :checkouts, only: [:new, :create]

  resources :teachers do
  	resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :get_total_price, :authenticate_user!

  def new
    @client_token = Braintree::ClientToken.generate
  end

  def create
    result = Braintree::Transaction.sale(
      amount: @total_price,
      payment_method_nonce: params[:payment_method_nonce],
      options: {
        submit_for_settlement: true
      }
    )

    if result.success?
      @timeslot.update(booked: true, user_id: current_user.id)
      flash[:success] = "Your booking is successful!"
      redirect_to root_path
    else
      flash[:danger] = "Payment failed!"
      redirect_to root_path
    end

  end


  private

  def get_total_price
    @timeslot = Timeslot.find(params[:timeslot])
    @schedule = @timeslot.schedule
    @subject = @schedule.subject
    @total_price = @subject.hourly_rate

  end
end

app/views/checkouts/new.html.erb
<div class="form">
  <%= form_for(:payment, url: checkouts_path(timeslot: @timeslot.id), html: { id: "payment-form" }) do |f| %>
    <div class="form-group">
      <header>
        <h1>Please enter your payment details</h1>
        <p>
          or you can make your payment through paypal
        </p>
      </header>
    </div>

    <div class="form-group", id="dropin-container">
    </div>

    <div class="form-group">
      <h4>Amount: RM<%= @total_price %></h4>
    </div>

    <div class="form-group">
      <%= f.submit "Pay", class: "btn btn-success btn-lg" %>
    </div>
  <% end %>
</div>

<script>
  braintree.setup("<%=@client_token%>", 'dropin', {
    container: 'dropin-container',
    form: 'payment-form'
  });
</script>